
name: Build and Publish NuGet Package

concurrency:
  group: publish
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    - name: Restore dependencies
      run: dotnet restore
      working-directory: src 

    - name: Build project
      run: dotnet build --configuration Release --no-restore
      working-directory: src 

    - name: Bump version if needed
      run: python ./Tools/bump_version.py

    - name: Push version bump
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git push --tags

    - name: Pack NuGet package
      run: dotnet pack --configuration Release --no-build --output ./artifacts
      working-directory: src 

    - name: Publish to NuGet
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: dotnet nuget push src/artifacts/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json
